Adding guide for creating imagery layers
Esri/arcgis-python-api pull request #1036
Opened 2021-06-24 06:55 UTC by rhea-j

Adding notebook guide to explain how we can create imagery using ArcGIS API for Python

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('home')`
    - `gis = GIS(profile="your_online_portal")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `<img src="base64str_here">` instead of `<img src="https://some.url">`? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

2021-06-25 06:11 UTC, rhea-j commented
@BP-Ent Could you go through this guide?

2021-06-25 18:59 UTC, BP-Ent commented on guide/06-imagery-and-raster-analysis/creating_imagery_layers.ipynb
> +{
<p>For this functionality to work in ArcGIS Online, Azure library packages for Python (Azure SDK for Python - azure-storage-blob: 12.1&lt;= version &lt;=12.8) needs to be pre-installed. Refer here for more information <a href="https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-install" target="_blank">https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-install</a></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-06-25 18:59 UTC, BP-Ent commented on guide/06-imagery-and-raster-analysis/creating_imagery_layers.ipynb
> +{
<p>By using the <a href="https://developers.arcgis.com/python/api-reference/arcgis.raster.analytics.html#copy-raster" target="_blank">copy_raster</a> <strong>function</strong><em> </em>you can create one imagery layer by mosaicking multiple images.</p><p> </p><ul><li>Using the&nbsp;<code>raster_type_name</code>&nbsp;parameter, you can specify the raster type, which identifies metadata such as georeferencing, acquisition date, sensor type, and band wavelengths, along with a raster format. The supported raster types can be found in the&nbsp;<a href="https://app.reviewnb.com/Esri/arcgis-python-api/pull/1036/#Supported-raster-types" target="_blank">table</a> at the end of this guide. </li></ul><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2021-06-25 18:59 UTC, BP-Ent commented on guide/06-imagery-and-raster-analysis/creating_imagery_layers.ipynb
> +{
<p>Below are some examples for satellite imagery for the Landsat and Pleiades satellites along with the appropriate <code>raster_type_name</code> and <code>raster_type_params</code>:</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2021-06-25 18:59 UTC, BP-Ent commented on guide/06-imagery-and-raster-analysis/creating_imagery_layers.ipynb
> +{
<p>The <a href="https://developers.arcgis.com/python/api-reference/arcgis.raster.analytics.html#copy-raster" target="_blank">copy_raster</a> function also enables you <strong>to</strong> create an imagery layer from just one image. This option supports all supported raster and image formats, multidimensional raster data, and configuration with various source types and compression settings. Use this option for simple imagery layers where advanced metadata is not needed.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-06-25 18:59 UTC, BP-Ent commented on guide/06-imagery-and-raster-analysis/creating_imagery_layers.ipynb
> +{
<p>In this guide, you've learned how to create imagery layers from your local raster data or data in your datastore using the copy_raster and create_image_collection functions. These functions provide a simple way of creating an imagery layer from a normal raster dataset, multidimensional datasets, and even satellite datasets. You have also seen how to create an imagery layer from either a single or multiple raster datasets. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1036/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='28'/>

2021-06-25 18:59 UTC, BP-Ent requested changes
Suggested changes made on reviewnb

2021-06-25 21:06 UTC, rhea-j commented
@BP-Ent Thank you for going through it. I have made the changes as per your suggestions.

2021-06-25 21:07 UTC, rhea-j commented
@priyankatuteja You had mentioned in the last call that we need to add the version from which the AGOL supports the functionality, but AGOL always moves forwards and users cant use an older version of it. So we don't need to specify the version. 

We have made all other changes.

2021-06-27 20:08 UTC, rhea-j commented
@priyankatuteja @AtmaMani 
It will be great if we could merge this guide as well.

2021-06-29 19:41 UTC, AtmaMani approved these changes

2021-06-29 19:41 UTC, merged