v190_minor_changes
Esri/arcgis-python-api pull request #1047
Opened 2021-07-01 14:12 UTC by mohi9282

Changes to items_metadata.yaml file

2021-07-01 14:16 UTC, achapkowski approved these changes

2021-07-01 14:23 UTC, achapkowski requested changes

2021-07-01 14:23 UTC, achapkowski commented on items_metadata.yaml
> +  url: https://www.arcgis.com/home/home/item.html?id=f19cbf3595de4bf898e7228a46b79ffd
remove home/home

2021-09-14 19:51 UTC, AtmaMani commented
@mohi9282 do we need this PR for 1.9.1? Can we close them?

2021-09-14 20:04 UTC, mohi9282 commented
@AtmaMani there was an issue with this PR so I ended up doing another one for the release. I will close this PR.

2021-09-14 20:04 UTC, closed without merging