Added MMDetection guide
Esri/arcgis-python-api pull request #1060
Opened 2021-07-15 15:19 UTC by kapil-varshney

Adds MMDetection guide

2021-07-21 04:32 UTC, priyankatuteja commented
@guneetmutreja  and @kapil-varshney Changes suggested to Guneet offline. Once incorporated in MMSegmantation guide, you can add the missing ones to this guide too.

2021-08-10 12:08 UTC, kapil-varshney commented
@guneetmutreja @priyankatuteja Can you please review?

2021-08-11 04:58 UTC, guneetmutreja commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>MMdetection is an open-source library with many popular and <strong>state-of-the-art</strong> object detection models. Through <code>arcgis.learn</code> we have provided a bridge to use the growing list of models provided by <strong>the</strong> MMDetection library. </p><p> </p><p>The MMdet team won the COCO 2018 object detection challenge. Their codebase, which is built with Pytorch, gradually evolved to include various models and methods. Although the detection task can be complex, the creators of MMDetection decomposed the models into different general components - Backbone, Neck, DenseHead, ROIExtractor<strong>,</strong> and ROIHead. With this abstraction the library is able to provide a multitude of single-stage (e.g. GHM, FCOS), two-stage (e.g. Double-Head R-CNN), multi-stage (e.g. Cascade R-CNN)<strong>,</strong> and other kinds of detection models. This abstraction-based approach also allows the development of models by changing the different components or even adding new ones. Read the MMDetection <a href="https://arxiv.org/pdf/1906.07155.pdf" target="_blank">paper</a> or checkout their <a href="https://github.com/open-mmlab/mmdetection" target="_blank">github repository</a> for more detail.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-08-11 04:58 UTC, guneetmutreja commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>Let's change the world imagery from input imagery parameter.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-08-11 04:59 UTC, guneetmutreja requested changes
Please incorporate the changes.

2021-08-11 05:12 UTC, kapil-varshney commented
> Please incorporate the changes.

Done. Thanks for the suggestions.

2021-08-11 06:50 UTC, guneetmutreja approved these changes
LGTM

2021-08-11 07:45 UTC, guneetmutreja commented
@BP-Ent Can you help to review the guide?

2021-08-11 16:21 UTC, BP-Ent commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>MMdetection is an open-source library containing many popular and state-of-the-art object detection models. Through <code>arcgis.learn</code>, we have provided a bridge to use the growing list of models provided by the MMDetection library. </p><p>In 2018, the MMdet team won the COCO object detection challenge. Their codebase, which is built with Pytorch, has gradually evolved to include various models and methods. Although the detection task can be complex, the creators of MMDetection decomposed the models into different general components - Backbone, Neck, DenseHead, ROIExtractor, and ROIHead. With this abstraction, the library is able to provide a multitude of single-stage (e.g. GHM, FCOS), two-stage (e.g. Double-Head R-CNN), multi-stage (e.g. Cascade R-CNN), and other detection models. This abstraction-based approach also allows the development of models either by changing the different components or even by adding new ones. Read the MMDetection <a href="https://arxiv.org/pdf/1906.07155.pdf" target="_blank">paper</a>, or checkout its <a href="https://github.com/open-mmlab/mmdetection" target="_blank">github repository</a>, for more details.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-08-11 16:21 UTC, BP-Ent commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>Follow the steps <a href="https://developers.arcgis.com/python/guide/install-and-set-up/#Install-deep-learning-dependencies" target="_blank">here</a> to install deep learning dependencies in ArcGIS Pro or your Anaconda environment. </p><p>ArcGIS Pro 2.8 users additionally need to install the CUDA toolkit (version 11), mmcv-full, and mmdet libraries. Follow these steps to do so: </p><ul><li>Download and install the latest CUDA toolkit version from&nbsp;<a href="https://developer.nvidia.com/cuda-downloads" target="_blank">here</a>.</li><li>Add the installed CUDA toolkit's bin folder path (typically, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin) to the (user or system) Path Environment Variables.</li><li>Run the following command in a cloned environment:</li><li><code>conda install -c esri mmcv-full mmdet</code></li></ul><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-08-11 16:21 UTC, BP-Ent commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>Using MMDetection with arcgis.learn is as simple as using any other object detection model in the library. The only additional step is providing the name of the model to be used when initializing the MMDetection model object.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2021-08-11 16:21 UTC, BP-Ent commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>The parameters required are: </p><ul><li><code>data</code>&nbsp;- the data object prepared using&nbsp;<code>prepare_data</code></li><li><code>model</code>&nbsp;- the name of the models from the list of supported models.</li></ul><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2021-08-11 16:21 UTC, BP-Ent commented on guide/14-deep-learning/Using MMDetection with `arcgis.learn`.ipynb
> +{
<p>For more information about the API, visit the <a href="https://developers.arcgis.com/python/api-reference/arcgis.learn.toc.html#mmdetection" target="_blank">API reference for MMDetection</a>. For a detailed object detection workflow, refer to a sample <a href="https://developers.arcgis.com/python/sample-notebooks/detecting-and-categorizing-brick-kilns-from-satellite-imagery/" target="_blank">notebook</a>.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1060/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2021-08-11 16:21 UTC, BP-Ent requested changes
Suggested changes made on reviewnb

2021-09-28 17:31 UTC, mohi9282 commented
@kapil-varshney - any updates on the requested changes? Changes need to be reviewed and merged ASAP as the guide is scheduled for V1.9.1.

cc: @AtmaMani @priyankatuteja

2021-09-30 22:35 UTC, mohi9282 commented
removing from v1.9.1 milestone per discussion with Kapil.

2021-12-02 10:56 UTC, kapil-varshney commented
@priyankatuteja Renamed the guide.

2021-12-02 11:03 UTC, priyankatuteja approved these changes

2021-12-02 11:03 UTC, priyankatuteja approved these changes

2021-12-02 11:06 UTC, merged