part1_sedf
Esri/arcgis-python-api pull request #1092
Opened 2021-09-07 20:59 UTC by mohi9282

New guide for SEDF: part1_sedf. Resolves issue /ArcGIS/geosaurus/issues/6847

2021-09-07 21:01 UTC, mohi9282 commented
@achapkowski the sedf guide part-1 is ready for your review. Atma has reviewed this already. The goal is to publish it with 1.9.1 release.

cc: @AtmaMani

2021-09-08 09:47 UTC, achapkowski reviewed
I normally refer to Spatially enabled DataFrame as **SeDF** not SEDF

2021-09-17 09:45 UTC, achapkowski approved these changes

2021-09-21 22:10 UTC, AtmaMani commented on guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
> +{
<p>Add a Note here using the same cell style as in the note at the very bottom:</p><p> </p><p>"</p><p>Note: Spatial Data Engineering using SeDF builds on top of core Data Engineering concepts in Python. If you are new to Pandas, NumPy and related libraries, we recommend you start with the <a href="part1-introduction-to-dataengineering/" target="_blank">Introduction to Data Engineering</a> guide series and then come here.</p><p>"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1092/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2021-09-21 22:10 UTC, AtmaMani commented on guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
> +{
<p><em>"GeoSeriesAccessor</em> and <em>GeoAccessor</em> classes are similar to <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series" target="_blank">pandas.Series</a> and <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame" target="_blank">pandas.DataFrame</a> objects however they do not need to be called repeatedly during the analysis for usage.  </p><p>Importing Geo will add spatial and geom namespaces to your dataframe and series resp. It is best practice to import Pandas followed by importing both the <em>GeoAccessor</em> and the <em>GeoSeriesAccessor</em> classes at the beginning of the analysis. Importing these classes registers their functionality with Pandas and allows you to start performing spatial operations. You may import the classes as follows: "  ---&gt; </p><p> </p><p>"<em>GeoSeriesAccessor</em> and <em>GeoAccessor</em> classes are similar to <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html#pandas.Series" target="_blank">pandas.Series</a> and <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html#pandas.DataFrame" target="_blank">pandas.DataFrame</a> objects. However, you do not work with them directly. Instead, you import them right after you import Pandas as shown in the snippet below. Importing these classes registers the spatial functionality with Pandas and allows you to start performing spatial operations on your DataFrames.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1092/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='13'/>

2021-09-21 22:10 UTC, AtmaMani commented on guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
> +{
<p>"However, we recommend using <code>arcpy</code> for better accuracy <strong>and support for a wider gamut of data sources"</strong></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1092/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-09-21 22:10 UTC, AtmaMani commented on guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
> +{
<p>The <code>area</code> property retrives the area of each buffer <strong>in the units of the DataFrame's spatial reference.</strong></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1092/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='48'/>

2021-09-21 22:10 UTC, AtmaMani commented on guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
> +{
<p>Let's <strong>now </strong>perform some basic Pandas operations on a SeDF. <strong>One of the benefits of the accessor pattern in SeDF is, the SeDF object is still of type 'DataFrame'. Thus, you can continue to perform regular Pandas DataFrame operations.</strong></p><p> </p><p>We will:</p><p>....</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1092/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='54'/>

2021-09-21 22:10 UTC, AtmaMani commented on guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
> +{
<p>Insert a plug to the primer guide series here. "If you would like to learn more about Pandas and data engineering with Pandas, checkout our [Data Engineering primer guide](part3-introduction-to-pandas/)</p><p> </p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1092/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='59'/>

2021-09-21 22:11 UTC, AtmaMani requested changes
@mohi9282 this is an excellent guide! I have asked for minor revisions, mostly text.

2021-09-23 15:43 UTC, mohi9282 commented
@AtmaMani I have updated the sample per the requested changes.

2021-09-24 16:25 UTC, AtmaMani approved these changes

2021-09-24 16:26 UTC, merged