Adds SQN model guide.
Esri/arcgis-python-api pull request #1509
Opened 2023-03-29 21:32 UTC by vbhv14

- [x] Added SQN model guide.

2023-03-29 21:34 UTC, vbhv14 commented
@BP-Ent requesting your review/feedback.

2023-09-11 21:21 UTC, jyaistMap requested changes
Visually the guide looks good when build locally. 

In all links to the `References` section, please change _References_ to _references_.  The upper case _R_ renders the link inactive when built for the website.

2023-09-11 21:23 UTC, jyaistMap commented on guide/14-deep-learning/point_cloud_classification_using_sqn.ipynb
> +{
<p>Change the text for the actual link to the references from <em>#References</em> to _#references_ </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1509/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2023-09-11 21:23 UTC, jyaistMap commented on guide/14-deep-learning/point_cloud_classification_using_sqn.ipynb
> +{
<p>Change the hyperlink text from <em>#References</em> to _#references_ </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1509/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2023-09-11 21:23 UTC, jyaistMap commented on guide/14-deep-learning/point_cloud_classification_using_sqn.ipynb
> +{
<p>Change hyperlink text to the references from <em>#References</em> to _#references_ </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1509/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2023-09-11 21:23 UTC, jyaistMap commented on guide/14-deep-learning/point_cloud_classification_using_sqn.ipynb
> +{
<p>Change hyperlink text to the references from <em>#References</em> to _#references_ </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/1509/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2023-10-19 11:20 UTC, vikashranjan26 approved these changes
LGTM

2023-11-28 09:24 UTC, priyankatuteja commented
> Visually the guide looks good when build locally.
> 
> * In all links to the `References` section, please change _References_ to _references_.  The upper case _R_ renders the link inactive when built for the website.

@jyaistMap  Why is this change suggested? Is that a requirement for all notebooks

2023-12-14 04:57 UTC, priyankatuteja approved these changes

2023-12-14 04:58 UTC, merged