Update clinic location allocation analysis
Esri/arcgis-python-api pull request #2122
Opened 2024-10-22 11:11 UTC by nanaeaubry

Update use of mapping methods and the symbols to use the Symbol Dataclasses.

2024-11-01 04:08 UTC, cariashuang0417 approved these changes
LGTM! 💯 
Note: Some images paths in notebook are out-of-dated. May need re-visit in the future to update the paths.

2025-01-15 19:27 UTC, jyaistMap requested changes
* submitted #2194 for updates

2025-01-16 10:33 UTC, nanaeaubry commented
@jyaistMap Thank you for all of this! Merged in your fixes

2025-01-16 20:45 UTC, jyaistMap approved these changes

2025-01-16 20:45 UTC, merged