Update River Turbidity Sample
Esri/arcgis-python-api pull request #2126
Opened 2024-10-22 12:16 UTC by nanaeaubry

remove use of credentials 
update to use new map methods

2024-10-30 03:53 UTC, cariashuang0417 requested changes
left a question and a comment for a little change needed

2024-10-30 14:54 UTC, nanaeaubry commented
<p>Oh you're right let's go with 'terrain'</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2126/discussion/#comment-2445778546'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-10-30 19:08 UTC, cariashuang0417 approved these changes

2025-01-15 19:26 UTC, jyaistMap requested changes
* submitted #2198 to make one small update

2025-01-16 10:32 UTC, nanaeaubry commented
@jyaistMap Thanks merged your change in!

2025-01-16 20:48 UTC, jyaistMap approved these changes

2025-01-16 20:48 UTC, merged