updates_for_finding_routes_for_applicance_sample
Esri/arcgis-python-api pull request #2130
Opened 2024-10-23 05:09 UTC by cariashuang0417

- updated map.content.draw and symbols
- updated to folder.add for fgdb item

Note: I am not able to test the outputs since the original csv data is missing. For symbols, I've tested on similar point and polyline feature layers, and they works. @nanaeaubry could you check if my formatting change for symbols are in line with new mapping module standards? Thanks :)

2024-10-23 08:49 UTC, nanaeaubry commented
@cariashuang0417 Looks good for symbols but left one comment about the draw method being on `content.draw` now

2024-10-23 08:50 UTC, nanaeaubry requested changes
small comment in notebook

2024-10-23 14:44 UTC, cariashuang0417 commented
> @cariashuang0417 Looks good for symbols but left one comment about the draw method being on `content.draw` now

ooops forgot to change the draw() method - just updated the PR for them

2024-10-23 14:54 UTC, nanaeaubry approved these changes
looooooks goooood :)

2024-10-23 23:10 UTC, ManushiM approved these changes

2025-01-21 16:33 UTC, jyaistMap approved these changes
# local build

* map cells look great:

<img width="688" alt="image" src="https://github.com/user-attachments/assets/04613ef3-a236-4b12-b922-b9f62c6008a7" />

<img width="725" alt="image" src="https://github.com/user-attachments/assets/05c3e022-b507-4ad2-97a9-0583f6942925" />

2025-01-21 16:34 UTC, merged