Add items to portal sample
Esri/arcgis-python-api pull request #2135
Opened 2024-10-23 09:36 UTC by nanaeaubry

Update to use new Folders and Folder class

2024-10-23 20:50 UTC, cariashuang0417 commented on samples/05_content_publishers/publishing_sd_shapefiles_and_csv.ipynb
>      "            search_result = gis.content.search(query=file_name, item_type=current_item_type)\n",
<pre class="ql-syntax" spellcheck="false">Line #4.        item = root_folder.add({}, data_dir + current_sd_file)   # .sd file is uploaded and a .sd file item is created
</pre><p>Need "title" and "item_type" for item_properties param, and ".result()" to get the Folder.add result - Same in some of the Folder.add code below.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2135/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='8'/>

2024-10-23 20:53 UTC, cariashuang0417 requested changes
Left a comment from nbreviewer above. Just need more info for "title" and "item_type" for item_properties param when doing `Folder.add`, and add `.result()` for getting the results of `Folder.add`

2024-11-09 00:55 UTC, jyaistMap requested changes
* submitted #2158 to add navigation and make small changes in formatting and content of dictionary - let me know if you think those don't make sense

2024-11-11 07:16 UTC, nanaeaubry commented
@jyaistMap Thank you merged it in :)

2024-12-02 22:56 UTC, jyaistMap approved these changes

2024-12-02 22:56 UTC, merged