Update OGC Sample
Esri/arcgis-python-api pull request #2136
Opened 2024-10-23 10:11 UTC by nanaeaubry

Update to use new map methods, folder classes, and layers module

2024-10-23 18:07 UTC, cariashuang0417 commented on samples/05_content_publishers/publish_ogc_services.ipynb
>     "outputs": [],
<pre class="ql-syntax" spellcheck="false">Line #3.    from arcgis.mapping import WebMap
</pre><p>This import can be removed</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2136/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2024-10-23 18:07 UTC, cariashuang0417 commented on samples/05_content_publishers/publish_ogc_services.ipynb
>     "outputs": [],
<pre class="ql-syntax" spellcheck="false">Line #11.    wms_item = root_folder.add(item_properties=dictItemData)
</pre><p><code>.result()</code> for the Folder.add() job result </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2136/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='32'/>

2024-10-23 18:07 UTC, cariashuang0417 commented on samples/05_content_publishers/publish_ogc_services.ipynb
>     "outputs": [],
<pre class="ql-syntax" spellcheck="false">Line #16.    wfs_item = root_folder.add(item_properties=dictItemData)
</pre><p><code>.result()</code> for the Folder.add() result </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2136/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='41'/>

2024-10-23 18:07 UTC, cariashuang0417 commented on samples/05_content_publishers/publish_ogc_services.ipynb
>     "outputs": [],
<pre class="ql-syntax" spellcheck="false">Line #8.               )
</pre><p>Same here - <code>.result()</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2136/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='46'/>

2024-10-23 18:09 UTC, cariashuang0417 requested changes
Some Folder.add are missing `.result()` - which I mentioned in the nbreviewer. Overall looks good to me 😃

2024-10-24 19:23 UTC, cariashuang0417 approved these changes

2024-11-08 20:24 UTC, jyaistMap approved these changes
* submitted #2156 and merged to update description

2024-11-08 20:24 UTC, merged