Update features edit sample
Esri/arcgis-python-api pull request #2137
Opened 2024-10-23 10:15 UTC by nanaeaubry

Use Folder add instead of ContentManager add

2024-10-23 15:03 UTC, cariashuang0417 commented on samples/05_content_publishers/updating_features_in_a_feature_layer.ipynb
> -{"cells": [{"cell_type": "markdown", "metadata": {}, "source": ["# Updating features in a feature layer\n", "\n", "As content publishers, you may be required to keep certain web layers up to date. As
<pre class="ql-syntax" spellcheck="false">Line #2.    item_prop = {'title':'USA Capitals spreadsheet ' + now_ts}
</pre><p>Need <code>"item_type": "CSV"</code> for item properties as a required key value pair :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2137/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2024-10-23 16:28 UTC, cariashuang0417 commented on samples/05_content_publishers/updating_features_in_a_feature_layer.ipynb
> -{"cells": [{"cell_type": "markdown", "metadata": {}, "source": ["# Updating features in a feature layer\n", "\n", "As content publishers, you may be required to keep certain web layers up to date. As
<p>Oops and <code>.result()</code> to get the Folder.add() result!</p>

2024-10-24 19:20 UTC, cariashuang0417 approved these changes

2024-11-08 18:59 UTC, jyaistMap requested changes
@nanaeaubry  - Can you please address the conflicts?

2024-11-27 00:42 UTC, jyaistMap approved these changes
looks good, thanks @nanaeaubry

2024-11-27 00:42 UTC, merged