sample notebook `fighting_california_forest_fires_using_spatial_analysis.ipynb` updated to incorporate the new map widget
Esri/arcgis-python-api pull request #2141
Opened 2024-10-24 21:29 UTC by tarunkukreja003

sample notebook `fighting_california_forest_fires_using_spatial_analysis.ipynb` updated to incorporate the new map widget

please use the playground portal account and api_data_owner account for creating the GIS object since the data is stored there

2024-10-25 06:01 UTC, cariashuang0417 commented on samples/04_gis_analysts_data_scientists/fighting_california_forest_fires_using_spatial_analysis.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #3.        if webmap.content.layers[0].properties['name'].startswith('At_Risk_Infrastructure'):
</pre><p><code>if lyr.properties['name'].startswith('At_Risk_Infrastructure'):</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2141/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='39'/>

2024-10-25 06:01 UTC, cariashuang0417 commented on samples/04_gis_analysts_data_scientists/fighting_california_forest_fires_using_spatial_analysis.ipynb
>    },
<pre class="ql-syntax" spellcheck="false">Line #4.        if webmap.content.layers[0].properties['name'].startswith('At_Risk_Infrastructure'):
</pre><p>Same as above - <code>﻿if lyr.properties['name'].startswith('At_Risk_Infrastructure'):</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2141/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='41'/>

2024-10-25 06:03 UTC, cariashuang0417 requested changes
Left comments for a little tweak in scripts. Overall looks good to me!

2024-10-25 06:38 UTC, nanaeaubry commented on samples/04_gis_analysts_data_scientists/fighting_california_forest_fires_using_spatial_analysis.ipynb
>    },
<p>Map doesn't take zoom as a parameter. You can move this to a cell below and do <code>m.zoom = 9</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2141/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2024-10-25 06:38 UTC, nanaeaubry commented on samples/04_gis_analysts_data_scientists/fighting_california_forest_fires_using_spatial_analysis.ipynb
>    },
<p>Same here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2141/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2024-10-25 06:38 UTC, nanaeaubry commented on samples/04_gis_analysts_data_scientists/fighting_california_forest_fires_using_spatial_analysis.ipynb
>    },
<p>Ditto</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2141/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='32'/>

2024-10-25 06:38 UTC, nanaeaubry commented on samples/04_gis_analysts_data_scientists/fighting_california_forest_fires_using_spatial_analysis.ipynb
>    },
<p>ditto</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2141/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='44'/>

2024-10-25 06:39 UTC, nanaeaubry requested changes
Small changes with zoom in the initializer

2024-11-08 18:50 UTC, jyaistMap requested changes
Please address @nanaeaubry's comments about removing the zoom integer from the _Map_ initialization and adding a cell under the map image that zooms:
```python
m.zoom = 9
```

2024-11-08 18:52 UTC, jyaistMap requested changes
Please change the cells @cariashuang0417 references as well.

2024-11-12 23:42 UTC, tarunkukreja003 commented
thanks for comments/suggestions, they are addressed

2024-11-13 08:58 UTC, nanaeaubry approved these changes

2024-11-13 18:02 UTC, jyaistMap approved these changes
* build website locally and looks good

2024-11-13 18:02 UTC, merged