`Using and updating GIS content` sample notebook revamped according to the new map widget
Esri/arcgis-python-api pull request #2160
Opened 2024-11-12 22:10 UTC by tarunkukreja003

`Using and updating GIS content` sample notebook is now revamped according to the new map widget

Major changes include:
1. The JSON of the web scene or web map is not changed anymore, instead, we use property setters to update the web maps and web scenes 
2. Properties and methods updated according to the new map widget

**NOTE**
PLEASE TEST AGAINST THIS PR https://github.com/ArcGIS/geoserpent/pull/190, THE NOTEBOOK CELLS WILL ONLY WORK IF THE CHANGES FROM THIS PR IS PULLED IN

2024-11-13 08:57 UTC, nanaeaubry requested changes
Left some comments in the notebook reviewer. Good start with this! :)

2024-11-26 19:46 UTC, jyaistMap commented
<p>I Agree with Nanae. Please remove this cell or explain why you are searching for a WebMap of this title, and why you are searching outside the organization.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2160/discussion/#comment-2472884437'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-11-27 00:19 UTC, jyaistMap requested changes
* more explanation needs added 
* we need to look at the scene section and examine what @nanaeaubry has said about how we shouldn't be setting layers or promoting workflows we don't want used

2025-01-10 00:36 UTC, tarunkukreja003 commented
Thanks @jyaistMap and @nanaeaubry for the suggestions and comments, I have commited changes, please review, thanks

2025-04-02 18:13 UTC, jyaistMap approved these changes
* looks good in a local build

2025-04-02 18:13 UTC, merged