2.4.0 changes to safe_streets_to_schools sample
Esri/arcgis-python-api pull request #2168
Opened 2024-11-19 18:29 UTC by ManushiM

changes made
1. Rendering and other map changes to reflect new map widget changes
2. Few changes to the markdown description.

Also tested this against https://github.com/ArcGIS/geoserpent/pull/190 and it works smoothly. 

refer to [ArcGIS:geosaurus/12343](https://github.com/ArcGIS/geosaurus/issues/12343)

-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? 
    - [ ] First block of imports are standard libraries
    - [ ] Second block are 3rd party libraries
    - [ ] Third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('home')` or `gis = GIS('pro')`
    - `gis = GIS(profile="your_online_portal")`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the `api_data_owner` user?
- [ ] If the notebook requires working with local data (such as CSV, FGDB, SHP, Raster files), upload the files as items to the [Geosaurus Online Org](geosaurus.maps.arcgis.com/) using `api_data_owner` account and change the notebook to first download and unpack the files.
- [ ] Code simplified & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `<img src="base64str_here">` instead of `<img src="https://some.url">`? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] Is your code formatted using [Jupyter Black](https://www.freecodecamp.org/news/auto-format-your-python-code-with-black/)? You can use Jupyter Black to format your code in the  notebook.
- [ ] **If this notebook showcases deep learning capabilities, please go through the following checklist:**
    - [ ] Are the inputs required for `Export Training Data Using Deep Learning` tool published on geosaurus org (api data owner account) and added in the notebook using `gis.content.get` function?
    - [ ] Is training data zipped and published as Image Collection? Note: Whole folder is zipped with name same as the notebook name.
    - [ ] Are the inputs required for model inferencing published on geosaurus org (api data owner account) and added in the notebook using `gis.content.get` function? Note: This includes providing test raster and trained model.
    - [ ] Are the inferenced results displayed using a webmap widget?
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @jyaistMap so he can add it to the list for the next deploy.

2024-11-20 07:26 UTC, cariashuang0417 approved these changes
Thanks for updates @ManushiM ! Just left some comments (mostly the same) for zoom level tweaks. Overall looks good!

I am not 100% sure about the arcade expression, so will need help on double check this from @nanaeaubry . I've just tested the symbols and renderers locally and all looks good on maps. Great job Manushi, and I learned a lot from your changes in advanced mapping. 😃

2024-11-20 07:59 UTC, nanaeaubry commented
@ManushiM Looks good, same comments as Shuang and the rendering looks correct.

2024-11-20 17:54 UTC, ManushiM commented
Thanks for the great feedback @cariashuang0417 and @nanaeaubry . I made the necessary changes.

2024-11-20 19:49 UTC, cariashuang0417 commented
All looks good! 🥇

2024-11-22 23:39 UTC, jyaistMap commented
<p>The zoom has to be performed after the map has been rendered. The code as is will draw the exact same widget if you were to run this code:</p><p><code>m1 = gis.map("Pasadena, California")</code></p><p><code>m1.zoom = 2</code></p><p><code>m1.basemap.basemap = "topo-vector"</code></p><p><code>m1</code></p><p> </p><p>Please move the <code>m1.zoom = 13</code> to its own cell after the map has been rendered. </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2487696874'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-11-22 23:41 UTC, jyaistMap commented
<p>Same issue as above. The map widget will not recognize a zoom level before it is rendered. It has to be rendered first and then the zoom can be applied.  <code>m2.zoom = 13</code> has to be in a cell on its own after the map has already been rendered. </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2487696894'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-11-22 23:57 UTC, jyaistMap requested changes
Hi @ManushiM 
* all the map cells need changed because the _zoom_ will not change the view of the map widget unless it's run after a map has been rendered. Maps appear the same no matter what zoom you set before being rendered:
![image](https://github.com/user-attachments/assets/d09eb697-42b1-4001-8df3-0986c4185f48)

The _zoom_ has to be run after:
![image](https://github.com/user-attachments/assets/88b195ec-f9f7-413c-b065-5260da677404)

* Please remove all the `mx.zoom = level` lines from the map cells and move them to a cell directly after the map has been rendered.

2024-11-27 17:22 UTC, ManushiM commented
@jyaistMap Thank you for the change recommendation for  `zoom` . I changed it only for cells where the map rendered was significantly different.

2024-11-27 21:02 UTC, jyaistMap commented
<p>The dark blue BicycleInjury points display much better in the map above. Please change the basemap to something other than <code>arcgis-dark-gray</code>,or just remove this cell entirely as the original map displays well.  </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2487697005'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-11-27 21:02 UTC, jyaistMap commented
<p>The blue points display poorly on the dark gray map.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2487697025'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-11-27 21:04 UTC, jyaistMap commented
<p>Can you select a basemap that allows all the symbology to display? The dark blue points and dark gray dangerous areas don't show up very well.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2487697061'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-11-27 21:06 UTC, jyaistMap commented
@ManushiM 
* I submitted PR against the branch on your fork to remove credentials and remove an empty cell
* The dark-gray basemap does not appear the best choice for the dark blue points and the dangerous area plots - can you adjust either the basemap or the symbology to display them more clearnly?

2024-12-03 23:33 UTC, ManushiM commented
@jyaistMap Thanks for your feedback! I followed the color scheme observed in the [notebook currently](https://developers.arcgis.com/python/latest/samples/safe-streets-to-schools/) as is. I'll make the recommended changes to the basemap.

2024-12-04 23:10 UTC, ManushiM commented
<p>I changed the color of the square shape (schools) to platinum to not conflict with the changed color for the accident type that was dark blue to orange.</p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2512813770'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-12-04 23:12 UTC, ManushiM commented
<p>I changed the dark blue <code>BicycleInjury</code> to orange and retained the dark gray basemap. </p>

---

 <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/2168/discussion/#comment-2487697005'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2025-04-02 18:37 UTC, jyaistMap approved these changes
* looks good in local build
  * dark gray basemap just before the conclusion could be changed for better visualiztion

2025-04-02 18:37 UTC, merged