provide data in dl samples
Esri/arcgis-python-api pull request #789
Opened 2020-09-09 03:48 UTC by priyankatuteja

- [x] automate_building_footprint_extraction_using_instance_segmentation
- [ ] 
-----

# Checklist

Please go through each entry in the below checklist and mark an 'X' if that condition has been met. Every entry should be marked with an 'X' to be get the Pull Request approved.

- [ ] All `import`s are in the first cell? First block of imports are standard libraries, second block are 3rd party libraries, third block are all `arcgis` imports? Note that in some cases, for samples, it is a good idea to keep the imports next to where they are used, particularly for uncommonly used features that we want to highlight.
- [ ] All `GIS` object instantiations are one of the following?
    - `gis = GIS()`
    - `gis = GIS('https://www.arcgis.com', 'arcgis_python', 'P@ssword123')`
    - `gis = GIS(profile="your_online_profile")`
    - `gis = GIS('https://pythonapi.playground.esri.com/portal', 'arcgis_python', 'amazing_arcgis_123')`
    - `gis = GIS(profile="your_enterprise_portal")`
- [ ] If this notebook requires setup or teardown, did you add the appropriate code to `./misc/setup.py` and/or `./misc/teardown.py`?
- [ ] If this notebook references any portal items that need to be staged on AGOL/Python API playground, did you coordinate with a Python API team member to stage the item the correct way with the api\_data\_owner user?
- [ ] Code refactored & split out across multiple cells, useful comments?
- [ ] Consistent voice/tense/narrative style? Thoroughly checked for typos?
- [ ] All images used like `<img src="base64str_here">` instead of `<img src="https://some.url">`? All map widgets contain a static image preview? (Call `mapview_inst.take_screenshot()` to do so)
- [ ] All file paths are constructed in an OS-agnostic fashion with `os.path.join()`? (Instead of `r"\foo\bar"`, `os.path.join(os.path.sep, "foo", "bar")`, etc.)
- [ ] **IF YOU WANT THIS SAMPLE TO BE DISPLAYED ON THE DEVELOPERS.ARCGIS.COM WEBSITE**, ping @ DavidJVitale so he can add it to the list for the next deploy

2020-09-21 22:12 UTC, AtmaMani commented on samples/04_gis_analysts_data_scientists/building_reconstruction_using_mask_rcnn.ipynb
>    },
<p>Should the connection be put back to 'home'?</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/789/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2020-09-21 22:12 UTC, AtmaMani commented on samples/04_gis_analysts_data_scientists/detecting_and_categorizing_brick_kilns_from_satellite_imagery.ipynb
>    },
<p>should the connection be 'home'?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/789/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2020-09-21 22:14 UTC, AtmaMani requested changes
A couple of notebooks create GIS connection with url, username, password. Otherwise changes look good.

2020-09-28 06:17 UTC, rohitgeo reviewed
Thanks @priyankatuteja for adding the sample data. This should make the samples much more approachable for our users.

2020-09-28 06:17 UTC, merged

2020-10-28 17:48 UTC, anneku commented
Thank you for adding all the sample data.

I am unable to access the sample training data for automate_building_footprint_extraction_using_instance_segmentation.ipynb
Automate Building Footprint Extraction using Deep learning

`training_data = gis.content.get('637825446a3641c2b602ee854776ed47')`

"The item you requested cannot be found. The item may have been deleted or you may have entered an incorrect URL."