changes as per issue 4036
Esri/arcgis-python-api pull request #840
Opened 2020-11-25 06:09 UTC by guneetmutreja

It contains required changes to be done to landcover mapping using sparse training data notebook as per discussion in issue #4036

2020-12-02 16:28 UTC, priyankatuteja commented on samples/04_gis_analysts_data_scientists/land_cover_classification_using_sparse_training_data.ipynb
>    },
<p>need to revert this back</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/840/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2020-12-02 16:28 UTC, priyankatuteja commented on samples/04_gis_analysts_data_scientists/land_cover_classification_using_sparse_training_data.ipynb
>    },
<p>You have removed the code for try it live that provides the training data. Can you please check this pull request again.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/840/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2020-12-02 16:29 UTC, priyankatuteja requested changes
@guneetmutreja Please have a look at the changes made in the pr. Looks like when you resolved the conflicts, some unintentional things have gone wrong.

2020-12-02 16:30 UTC, priyankatuteja requested changes
@guneetmutreja Please have a look at the changes made in the pr. Looks like when you resolved the conflicts, some unintentional things have gone wrong.

2020-12-03 07:16 UTC, guneetmutreja commented
Closing PR because some original changes were deleted. Will raise a new PR with the required changes.

2020-12-03 07:16 UTC, closed without merging