landcover classification using unet bug resolved
Esri/arcgis-python-api pull request #848
Opened 2020-12-03 10:59 UTC by guneetmutreja

Contains bug fixes mentioned in issue: https://github.com/ArcGIS/geosaurus/issues/5086

2020-12-07 17:12 UTC, priyankatuteja commented on samples/04_gis_analysts_data_scientists/land_cover_classification_using_unet.ipynb
>     "metadata": {},
<p>agol_gis or agol (lowercase variable name)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/848/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='33'/>

2020-12-07 17:13 UTC, priyankatuteja commented on samples/04_gis_analysts_data_scientists/land_cover_classification_using_unet.ipynb
>     "metadata": {},
<p>agol_gis or agol (lowercase variable name)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/848/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='33'/>

2020-12-07 17:13 UTC, priyankatuteja requested changes
Could you resolve merge conflicts and change the variable  name to lowercase

2020-12-07 17:13 UTC, priyankatuteja commented on samples/04_gis_analysts_data_scientists/land_cover_classification_using_unet.ipynb
>     "metadata": {},
<p>agol_gis or agol (lowercase variable name)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Esri/arcgis-python-api/pull/848/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='33'/>

2020-12-13 16:55 UTC, AtmaMani commented
@guneetmutreja can you address the comments and resolve the merge conflicts?

2020-12-14 04:36 UTC, guneetmutreja commented
@priyankatuteja  the changes you suggested, are implemented. Please review those. Thanks.

2020-12-14 04:36 UTC, guneetmutreja commented
@priyankatuteja  the changes you suggested, are implemented. Please review those. Thanks.

2020-12-14 04:47 UTC, guneetmutreja commented
Changes already merged with master.

2020-12-14 04:47 UTC, closed without merging